# Generated by Django 2.1.5 on 2019-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
