# Generated by Django 2.1.5 on 2019-01-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
    ]
